### ISSUE TITLE
Updating patient interface post acceptance/denial of consultation requests

### ISSUE THREAD

**Issue by 007vedant** [purplepotion/Elixir#28]
Letting the patient know if the consultation requests raised by him earlier are accepted or declined via notification or some other feature.

**Comment by aksamota** [comment]
We can create another field in notification which represents the type of notification. If it's a consent request notification, it will have the approve/decline functionality, else it will just have the description about the acceptance/denial of the consultation request.

**Comment by 007vedant** [comment]
Backend part of the issue is resolved via PR #34

**Comment by aksamota** [comment]
Frontend part of the issue resolved.
